### ISSUE TITLE
Request to add a paper

### ISSUE THREAD

**Issue by tsun** [52CV/ICCV-2023-Papers#3]
Hi, thanks for this wonderful repo!

Could you add a paper on Active Domain Adaptation to your repo?
"Local Context-Aware Active Domain Adaptation"
Paper: [https://arxiv.org/abs/2208.12856](https://arxiv.org/abs/2208.12856)
Code: [https://github.com/tsun/LADA](https://github.com/tsun/LADA)

**Comment by 52CV** [comment]
ok
