### ISSUE TITLE
Request to add a paper "MagicFusion: Boosting Text-to-Image Generation Performance by Fusing Diffusion Models"

### ISSUE THREAD

**Issue by MagicFusion** [52CV/ICCV-2023-Papers#4]
Hi, thanks for this wonderful repo!

Could you add a paper on Image Generation or Diffusion Models to your repo?
"MagicFusion: Boosting Text-to-Image Generation Performance by Fusing Diffusion Models"
Paper: https://openaccess.thecvf.com/content/ICCV2023/papers/Zhao_MagicFusion_Boosting_Text-to-Image_Generation_Performance_by_Fusing_Diffusion_Models_ICCV_2023_paper.pdf
Code: https://github.com/MagicFusion/MagicFusion.github.io
Project: https://magicfusion.github.io/

**Comment by 52CV** [comment]
ok
